apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tail-aware-eos-pvc
  namespace: ucsc-hsc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 512Gi
